use serde::{Deserialize, Serialize};

use crate::SimFloat;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SimVec2 {
    pub x: SimFloat,
    pub y: SimFloat,
}

impl SimVec2 {
    pub const ZERO: Self = Self {
        x: SimFloat::ZERO,
        y: SimFloat::ZERO,
    };

    #[inline]
    pub const fn new(x: SimFloat, y: SimFloat) -> Self {
        Self { x, y }
    }

    /// Dot product.
    #[inline]
    pub fn dot(self, rhs: Self) -> SimFloat {
        self.x * rhs.x + self.y * rhs.y
    }

    /// Squared length (no sqrt needed).
    #[inline]
    pub fn length_squared(self) -> SimFloat {
        self.dot(self)
    }

    /// Length (magnitude).
    #[inline]
    pub fn length(self) -> SimFloat {
        self.length_squared().sqrt()
    }

    /// Returns a unit vector in the same direction, or ZERO if length is zero.
    #[inline]
    pub fn normalize(self) -> Self {
        let len = self.length();
        if len == SimFloat::ZERO {
            return Self::ZERO;
        }
        self / len
    }

    /// Squared distance between two points.
    #[inline]
    pub fn distance_squared(self, other: Self) -> SimFloat {
        (self - other).length_squared()
    }

    /// Distance between two points.
    #[inline]
    pub fn distance(self, other: Self) -> SimFloat {
        (self - other).length()
    }
}

// -- Arithmetic operators (generated by macro) --
crate::vector_ops::impl_vector_ops!(SimVec2 { x, y });

#[cfg(test)]
#[path = "tests/vec2_tests.rs"]
mod tests;
