use serde::{Deserialize, Serialize};

use crate::SimFloat;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SimVec3 {
    pub x: SimFloat,
    pub y: SimFloat,
    pub z: SimFloat,
}

impl SimVec3 {
    pub const ZERO: Self = Self {
        x: SimFloat::ZERO,
        y: SimFloat::ZERO,
        z: SimFloat::ZERO,
    };

    #[inline]
    pub const fn new(x: SimFloat, y: SimFloat, z: SimFloat) -> Self {
        Self { x, y, z }
    }

    /// Dot product.
    #[inline]
    pub fn dot(self, rhs: Self) -> SimFloat {
        self.x * rhs.x + self.y * rhs.y + self.z * rhs.z
    }

    /// Cross product.
    #[inline]
    pub fn cross(self, rhs: Self) -> Self {
        Self::new(
            self.y * rhs.z - self.z * rhs.y,
            self.z * rhs.x - self.x * rhs.z,
            self.x * rhs.y - self.y * rhs.x,
        )
    }

    /// Squared length (no sqrt needed).
    #[inline]
    pub fn length_squared(self) -> SimFloat {
        self.dot(self)
    }

    /// Length (magnitude).
    #[inline]
    pub fn length(self) -> SimFloat {
        self.length_squared().sqrt()
    }

    /// Returns a unit vector in the same direction, or ZERO if length is zero.
    #[inline]
    pub fn normalize(self) -> Self {
        let len = self.length();
        if len == SimFloat::ZERO {
            return Self::ZERO;
        }
        self / len
    }

    /// Squared distance between two points.
    #[inline]
    pub fn distance_squared(self, other: Self) -> SimFloat {
        (self - other).length_squared()
    }

    /// Distance between two points.
    #[inline]
    pub fn distance(self, other: Self) -> SimFloat {
        (self - other).length()
    }
}

// -- Arithmetic operators (generated by macro) --
crate::vector_ops::impl_vector_ops!(SimVec3 { x, y, z });

#[cfg(test)]
#[path = "tests/vec3_tests.rs"]
mod tests;
